name: Main

run-name: ${{ github.actor }} building code and running tests

env:
  BUILD_TYPE: Debug

on: [push]

jobs:
  MainTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Initialize and update submodules
        run: git submodule update --init --recursive
      - run: |
          ls ${{ github.workspace }}
      - name: Install dependedcies
        run:  sudo ./scripts/install_dependency.sh
      - name: Build and run tasks
        run: ./scripts/run_tests.sh
